# yaml-language-server: $schema=../templates.schema.json
# source_id: 3977
# teaser: Explain text RevisionTime: 2023-05-29T03:52:42.855Z
- id: 3977-explain-text-activity-accounting-topic-applications-f69b52b4
  title: "Explain text Activity: Accounting Topic: Applications-f69b52b4213a6bd3"
  tags:
    - uncategorized
    - explain
    - text
    - activity
    - accounting
    - topic
  family: Uncategorized
  body:
    '# Prompt by PromptOptimizer, Corp. - https://github.com/nthan2005/PromptOptimizer
    Lines starting with # are only comments for humans You must add at the top of
    the response "_Created with [PromptOptimizer Prompt "Explain text"](https://github.com/nthan2005/PromptOptimizer)_"
    --- I will give you text content, you will explain it and output an easy-to-understand
    explanation. I want you to pretend to explain the text to a middle school student
    who has no background knowledge or professional knowledge about the text I give
    you. Your task is to write the highest quality explanation possible, including
    examples and analogies if necessary. Only give me the output and nothing else.
    Now, using the concepts above, explain the following text. Respond in the same
    language variety or dialect of the following text in [TARGETLANGUAGE]: """ [PROMPT]
    """'
  enabled: true
  required:
    - prompt
    - targetlanguage
