# yaml-language-server: $schema=../templates.schema.json
# source_id: 3985
# teaser: Get function for any code RevisionTime: 2023-09-28T12:33:01.939Z
- id: 3985-codes-function-activity-crm-topic-applications-f69b52b4213a6
  title: "Codes Function Activity: CRM Topic: Applications-f69b52b4213a6bd3"
  tags:
    - uncategorized
    - codes
    - function
    - activity
    - crm
    - topic
  family: Uncategorized
  body:
    '# Prompt by PromptOptimizer, Corp. - https://github.com/nthan2005/PromptOptimizer
    Lines starting with # are only comments for humans You must add at the top of
    the response "_Created with [PromptOptimizer Prompt "Codes Function"](https://github.com/nthan2005/PromptOptimizer)_"
    --- What is the function of the following code: [PROMPT] Explain that on [TARGETLANGUAGE]'
  enabled: true
  required:
    - prompt
    - targetlanguage
