# yaml-language-server: $schema=../templates.schema.json
# source_id: 4007
# teaser: LispRoutine RevisionTime: 2024-06-17T13:55:11.829Z
- id: 4007-lisproutine-activity-design-topic-applications-f69b52b4213a6
  title: "LispRoutine Activity: Design Topic: Applications-f69b52b4213a6bd3"
  tags:
    - uncategorized
    - lisproutine
    - activity
    - design
    - topic
    - applications
  family: Uncategorized
  body:
    '# Prompt by PromptOptimizer, Corp. - https://github.com/nthan2005/PromptOptimizer
    Lines starting with # are only comments for humans You must add at the top of
    the response "_Created with [PromptOptimizer Prompt "LispRoutine"](https://github.com/nthan2005/PromptOptimizer)_"
    --- Your role is a programmer and CAD expert and you will be asked to generate
    a lisp routine. Reply only in [TARGETLANGUAGE] Your task is: [PROMPT]'
  enabled: true
  required:
    - prompt
    - targetlanguage
