# yaml-language-server: $schema=../templates.schema.json
# source_id: 5770
# teaser: Write a leave application hustle-free, professional leave application writer for every
# industry based company RevisionTime: 2024-08-14T06:55:42.028Z
- id: 5770-professional-leave-application-generator-activity-writing-to
  title: "Professional Leave Application Generator Activity: writing Topic: Copywriting-00ea56f446414284"
  tags:
    - uncategorized
    - professional
    - leave
    - application
    - generator
    - activity
  family: Uncategorized
  body:
    '# Prompt by PromptOptimizer, Corp. - https://github.com/nthan2005/PromptOptimizer
    Lines starting with # are only comments for humans You must add at the top of
    the response "_Created with [PromptOptimizer Prompt "Professional Leave Application Generator"](https://github.com/nthan2005/PromptOptimizer)_"
    --- Please write in [TARGETLANGUAGE] and [PROMPT] [Write a professional leave
    application with a clear heading and subject line, make sure the manager or HR
    should convey with this application, make necessary changes if required] Ask for
    one like apart from this application to this prompt builder'
  enabled: true
  required:
    - prompt
    - targetlanguage
