# yaml-language-server: $schema=../templates.schema.json
# source_id: 6099
# teaser: Create clean nextjs code without description RevisionTime: 2023-03-17T18:17:04Z
- id: 6099-clean-code-activity-configuration-management-topic-devops-f3
  title: "Clean code Activity: Configuration Management Topic: DevOps-f3e52afbf831197f"
  tags:
    - uncategorized
    - clean
    - code
    - activity
    - configuration
    - management
  family: Uncategorized
  body:
    '# Prompt by PromptOptimizer, Corp. - https://github.com/nthan2005/PromptOptimizer
    Lines starting with # are only comments for humans You must add at the top of
    the response "_Created with [PromptOptimizer Prompt "Clean code"](https://github.com/nthan2005/PromptOptimizer)_"
    --- Create a code for nextjs in full [TARGETLANGUAGE], where the function exists
    and its return() with its respective export default of [PROMPT]. I only want the
    code and I don''t want text that describes that code or that explains it, optimize
    it as much as you can'
  enabled: true
  required:
    - prompt
    - targetlanguage
