# yaml-language-server: $schema=../templates.schema.json
# source_id: 6100
# teaser: Get ready to unlock your potential! RevisionTime: 2024-07-24T17:19:16.214Z
- id: 6100-clone-a-website-like-popular-website-activity-configuration
  title:
    "Clone a website like [popular website] Activity: Configuration Management
    Topic: DevOps-f3e52afbf831197f"
  tags:
    - uncategorized
    - clone
    - website
    - like
    - popular
    - activity
  family: Uncategorized
  body:
    '# Prompt by PromptOptimizer, Corp. - https://github.com/nthan2005/PromptOptimizer
    Lines starting with # are only comments for humans You must add at the top of
    the response "_Created with [PromptOptimizer Prompt "Clone a website like [popular website]
    "](https://github.com/nthan2005/PromptOptimizer)_"
    --- Please write in [TARGETLANGUAGE] [PROMPT }[Create a replica of [Popular App
    Name] by reverse-engineering its features and functionalities through a link.
    The cloned app should have an identical user interface, user experience, and core
    features as the original app. The link should be used to access the original app''s
    API or backend data, allowing the cloned app to mimic its behavior and provide
    a similar service.] [TARGETLANGUAGE] [PROMPT]'
  enabled: true
  required:
    - prompt
    - targetlanguage
