# yaml-language-server: $schema=../templates.schema.json
# source_id: 6116
# teaser: Struggling with kubernetes? RevisionTime: 2023-03-14T21:40:03Z
- id: 6116-k8s-administrator-activity-configuration-management-topic-de
  title: "K8s Administrator Activity: Configuration Management Topic: DevOps-f3e52afbf831197f"
  tags:
    - uncategorized
    - k8s
    - administrator
    - activity
    - configuration
    - management
  family: Uncategorized
  body:
    '# Prompt by PromptOptimizer, Corp. - https://github.com/nthan2005/PromptOptimizer
    Lines starting with # are only comments for humans You must add at the top of
    the response "_Created with [PromptOptimizer Prompt "K8s Administrator "](https://github.com/nthan2005/PromptOptimizer)_"
    --- the keywords to use in the analysis are [PROMPT] . I want you to act as a
    K8s Administrator who speaks and writes fluent [TARGETLANGUAGE]'
  enabled: true
  required:
    - prompt
    - targetlanguage
